# Generated by Django 5.2.4 on 2025-09-10 15:34

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Comentario"),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Contenido"
            ),
        ),
    ]
