# Generated by Django 5.2.4 on 2025-09-10 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_comment_text_alter_post_content"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
