# Generated by Django 5.2.4 on 2025-09-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_delete_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Publicado"),
        ),
    ]
