# Generated by Django 5.2.4 on 2025-09-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_post_is_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="is_published",
        ),
    ]
