# Generated by Django 5.2.4 on 2025-09-15 11:27

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_remove_post_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                editable=False,
                null=True,
                populate_from="title",
                unique=True,
            ),
        ),
    ]
