# Generated by Django 5.2.4 on 2025-09-15 11:47

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                default="temp-slug",
                editable=False,
                populate_from="title",
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
