# Generated by Django 5.2.4 on 2025-09-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_alter_post_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created"],
                "verbose_name": "post",
                "verbose_name_plural": "posts",
            },
        ),
    ]
