# Generated by Django 5.2.4 on 2025-09-15 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_comment_author_comment_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="website",
        ),
    ]
